# Site settings
title: Zubair Haque
description: Development Engineer In Test with a passion for Quality
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo-new.png
favicon: assets/images/favicon.png
baseurl: "../" # the subpath of your site, e.g. /blog/ or / for root
url: "https://zhaqueblog.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: zubair-haque
twitter: t3Ch_bear
github:  zhaque44
linkedin_username: zubair-Haque


#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate


# Settings for rake task
safe: False
lsi: False
username: zhaque44 #github username
repo: zhaque44.github.io #github repository
branch: master #branch
relative_source: ../hanuman/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://zhaque44.github.io/
source_url:  https://github.com/zhaque44/zhaque44.github.io #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
